name: 📑 Docs
description: Suggest Improvment for the docs.
title: "[Docs] <description>"
labels: ["📄 docs",]
body:
  - type: textarea
    id: description
    attributes:
      label: Description
      description: A breif description of the issue
    validations:
      required: true
  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots
      description: Please add screenshots if applicable
    validations:
      required: false
   - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](https://github.com/creative-tutorials/shopercase/blob/main/CODE_OF_CONDUCT.md)
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
